### PR TITLE
added the sorting function

### PR DESCRIPTION
**Pull request by raji2004**
please merge

### CODE REVIEW

**Comment by raji2004** [comment]
Oh and although u might not need it this is my personal advice you should use an object to define everything u want in your to-do list instead of giving them individual list it's cleans up your to-do at the same time makes your js look neat but u only have to set your state onces

**Comment by sanskaromar** [comment]
Thanks for the suggestion. I am planning to incorporate that soon.

**Comment by raji2004** [comment]
@sanskaromar how come you haven't merged is my code base?

**Review by sanskaromar — CHANGES_REQUESTED** [review]
- It doesn't work as expected. Somehow the tasks aren't getting filtered as expected.
- The position for the button that allows filtering is too far top-right. Please correct that.

**Comment by raji2004** [comment]
> * It doesn't work as expected. Somehow the tasks aren't getting filtered as expected.
> * The position for the button that allows filtering is too far top-right. Please correct that.

Alright then

**Comment by sanskaromar** [comment]
@raji2004 Are you still working on this?

**Comment by raji2004** [comment]
Yes

**Pull request closed without merging**
